### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by StasB93R** [iview/iview-ssr-test#1]
These dependencies were not found:

* ~plugins/iview/src/styles/index.less in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue
* ~/plugins/iview/src/index.js in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/components/button.vue

To install them, you can run: npm install --save ~plugins/iview/src/styles/index.less ~/plugins/iview/src/index.js

This relative module was not found:

* ./iview/src/iview.js in ./plugins/iview.js

thats what i get when i press npm run dev

**Comment by lcx960324** [comment]
Thanks for your feedback. Since we use submodule in this repo, it's hard for us to accept contributions right now(we've accessed an iview fork as git submodule in personal repo). So it's normal that you cannot get these dependencies.

**Comment by lcx960324** [comment]
We've update the project structure. Now you can contribute your code by following the README. Thanks for your attention.
