### ISSUE TITLE
run dev情况下正常，但是run build后渲染错误

### ISSUE THREAD

**Issue by Maisoo1** [iview/iview-ssr-test#2]
您好，我按照plugins引入iview的方式，dev下可以正常，但是build后渲染出现异常：
我用的官方的Menu组件：
`<Menu>
                <Submenu name="1">
                    <span slot="title">
                        <Icon type="ios-paper"></Icon>
                        内容管理
                    </span>
                    <Menu-item name="1-1">文章管理</Menu-item>
                    <Menu-item name="1-2">评论管理</Menu-item>
                    <Menu-item name="1-3">举报管理</Menu-item>
                </Submenu>
                <Submenu name="2">
                    <span slot="title">
                        <Icon type="ios-people"></Icon>
                        用户管理
                    </span>
                    <Menu-item name="2-1">新增用户</Menu-item>
                    <Menu-item name="2-2">活跃用户</Menu-item>
                </Submenu>
                <Submenu name="3">
                    <span slot="title">
                        <Icon type="stats-bars"></Icon>
                        统计分析
                    </span>
                    <Menu-group title="使用">
                        <Menu-item name="3-1">新增和启动</Menu-item>
                        <Menu-item name="3-2">活跃分析</Menu-item>
                        <Menu-item name="3-3">时段分析</Menu-item>
                    </Menu-group>
                    <Menu-group title="留存">
                        <Menu-item name="3-4">用户留存</Menu-item>
                        <Menu-item name="3-5">流失用户</Menu-item>
                    </Menu-group>
                </Submenu>
            </Menu>`

build后，只渲染后面两个菜单

另外，试了Icon组件也是：
`<div><Icon type="stats-bars"></Icon></div><div><Icon type="stats-paper"></Icon></div>`
2个Icon
dev下正常，build后就不显示

请教下这是怎么回事，麻烦了！

**Comment by lcx960324** [comment]
Since we haven't finished all test cases, we are not sure where the problem come from. Please paste your code on code platform like jsfiddle and we'll check it. Thank you.
